export const POST_NEW_QUESTION_REQUEST = "POST_NEW_QUESTION_REQUEST";
export const POST_NEW_QUESTION_SUCCESS = "POST_NEW_QUESTION_SUCCESS";
export const POST_NEW_QUESTION_FAILURE = "POST_NEW_QUESTION_FAILURE";
